/**
 * driverTabGuideRegistry.js — UX-C1
 * Human guide copy for each Drivers subtab.
 *
 * Each entry answers:
 *  - ¿Para qué entro aquí?
 *  - ¿Qué debo mirar?
 *  - ¿Qué hago después?
 */

const DRIVER_TAB_GUIDE_REGISTRY = {
  drivers_supply: {
    id: 'drivers_supply',
    title: 'Supply Overview',
    oneLinePurpose: 'Te muestra cómo está evolucionando el supply de conductores semana a semana.',
    whatYouCanDo: 'Ver activos, viajes, churn, reactivados y crecimiento neto. Detectar si la base crece o se deteriora.',
    howToUse: 'Revisa la tendencia semanal. Si el net growth es negativo varias semanas seguidas, hay un problema de retención que necesita acción.',
    decisionItSupports: '¿La base de conductores está creciendo o se está perdiendo? ¿Necesito campañas de reactivación?',
    nextStep: 'Si detectas caída, revisa Action Queues para identificar a quién contactar primero.',
    dataUnavailableMessage: 'La fuente operativa de supply no pudo cargarse. Verifica en Data Foundation que el refresco de datos esté al día.',
    audience: 'supervisor, strategy',
  },
  drivers_lifecycle: {
    id: 'drivers_lifecycle',
    title: 'Lifecycle Intelligence',
    oneLinePurpose: 'Te muestra en qué etapa del ciclo de vida está cada conductor.',
    whatYouCanDo: 'Ver distribución por segmento (activo, dormido, churn, nuevo). Entender cómo se distribuye tu flota.',
    howToUse: 'Observa qué porcentaje de conductores está en cada etapa. Si hay muchos en "dormido" o "churn reciente", hay oportunidad de reactivación.',
    decisionItSupports: '¿Dónde está concentrada mi flota? ¿Tengo más conductores dormidos que activos?',
    nextStep: 'Si hay muchos en churn reciente, crea una campaña de reactivación desde Campaign Intelligence.',
    dataUnavailableMessage: 'No se pudo leer la fuente operativa de lifecycle. Revisa Data Foundation u Operational Health.',
    audience: 'supervisor, strategy',
  },
  drivers_diagnostic: {
    id: 'drivers_diagnostic',
    title: 'Supply Diagnostics',
    oneLinePurpose: 'Te da un diagnóstico detallado del estado de la flota y sus brechas.',
    whatYouCanDo: 'Identificar problemas estructurales: baja cobertura de datos, gaps de actividad, conductores sin teléfono.',
    howToUse: 'Revisa los indicadores de cobertura. Si hay muchos conductores sin teléfono, las campañas de contacto serán menos efectivas.',
    decisionItSupports: '¿Mis datos están completos para operar? ¿Hay brechas que bloquean la ejecución?',
    nextStep: 'Si hay gaps de datos, repórtalos al equipo de Data Quality antes de crear campañas.',
    dataUnavailableMessage: 'El diagnóstico no pudo ejecutarse. Verifica la conectividad con la fuente operativa en Data Foundation.',
    audience: 'supervisor, admin',
  },
  drivers_behavior_benchmarking: {
    id: 'drivers_behavior_benchmarking',
    title: 'Behavioral Intelligence',
    oneLinePurpose: 'Te muestra cómo se comportan los conductores comparados con benchmarks de su segmento.',
    whatYouCanDo: 'Comparar actividad individual vs. promedio del segmento. Identificar conductores con bajo rendimiento relativo.',
    howToUse: 'Filtra por segmento o ciudad. Los conductores muy por debajo del benchmark de su grupo son candidatos a intervención.',
    decisionItSupports: '¿Quién está operando significativamente por debajo de su potencial?',
    nextStep: 'Conductores con bajo benchmark relativo pueden priorizarse en Action Queues.',
    dataUnavailableMessage: 'La fuente de comportamiento no está disponible. Verifica que los datos de actividad estén actualizados.',
    audience: 'strategy',
  },
  drivers_behavioral_alerts: {
    id: 'drivers_behavioral_alerts',
    title: 'Behavioral Alerts',
    oneLinePurpose: 'Te avisa cuando un conductor muestra un cambio abrupto en su comportamiento.',
    whatYouCanDo: 'Ver alertas de caída súbita de actividad, cambio de patrones horarios, o inactividad inesperada.',
    howToUse: 'Revisa las alertas activas. Las de conductores de alto valor que caen de repente son las más urgentes.',
    decisionItSupports: '¿Hay conductores que estaban bien y de pronto dejaron de operar?',
    nextStep: 'Si un conductor de alto valor tiene alerta, considéralo para contacto prioritario.',
    dataUnavailableMessage: 'Las alertas comportamentales no pudieron calcularse. Verifica la fuente operativa de actividad.',
    audience: 'supervisor, strategy',
  },
  drivers_fleet_leakage: {
    id: 'drivers_fleet_leakage',
    title: 'Fleet & Leakage Intelligence',
    oneLinePurpose: 'Te muestra dónde se está "fugando" la flota: conductores que dejan de operar sin explicación clara.',
    whatYouCanDo: 'Identificar patrones de abandono, ciudades con mayor fuga, y momentos críticos donde se pierde supply.',
    howToUse: 'Revisa las tasas de fuga por ciudad y por segmento. Las ciudades con mayor leakage necesitan atención inmediata.',
    decisionItSupports: '¿Dónde estoy perdiendo más conductores y por qué?',
    nextStep: 'Focaliza campañas de retención en las ciudades/segmentos con mayor fuga.',
    dataUnavailableMessage: 'Los datos de fuga de flota no están disponibles. Revisa la actualización de datos en Data Foundation.',
    audience: 'strategy',
  },
  drivers_behavioral_patterns: {
    id: 'drivers_behavioral_patterns',
    title: 'Behavioral Patterns',
    oneLinePurpose: 'Te muestra patrones recurrentes en el comportamiento de los conductores.',
    whatYouCanDo: 'Ver patrones de horarios, días de actividad, y ritmos operativos que caracterizan a cada segmento.',
    howToUse: 'Usa esta información para entender cuándo y cómo operan tus conductores. Ayuda a planificar momentos de contacto.',
    decisionItSupports: '¿Cuándo y cómo operan mis conductores? ¿Cuál es el mejor momento para contactarlos?',
    nextStep: 'Usa los patrones para elegir horarios de contacto en campañas CRM.',
    dataUnavailableMessage: 'Los patrones comportamentales no pudieron calcularse. Verifica la fuente operativa.',
    audience: 'strategy',
  },
  drivers_recoverability: {
    id: 'drivers_recoverability',
    title: 'Loyalty & Recoverability',
    oneLinePurpose: 'Te dice qué tan recuperable es un conductor inactivo basándose en su historia.',
    whatYouCanDo: 'Ver scoring de recuperabilidad por conductor. Priorizar a los que tienen mayor probabilidad de volver.',
    howToUse: 'Filtra conductores con alta recuperabilidad. Estos son los mejores candidatos para campañas de reactivación.',
    decisionItSupports: '¿A quién vale la pena contactar? ¿Quién tiene mayor chance de volver a operar?',
    nextStep: 'Incluye conductores de alta recuperabilidad en tu próxima campaña de reactivación.',
    dataUnavailableMessage: 'El scoring de recuperabilidad no está disponible. Verifica la fuente operativa.',
    audience: 'supervisor, strategy',
  },
  drivers_operational_intelligence: {
    id: 'drivers_operational_intelligence',
    title: 'Operational Intelligence',
    oneLinePurpose: 'Te da una visión operativa consolidada del estado de la flota con métricas accionables.',
    whatYouCanDo: 'Ver métricas operativas agregadas: utilización, eficiencia, gaps de cobertura por zona/turno.',
    howToUse: 'Revisa los indicadores operativos clave. Identifica zonas o turnos donde faltan conductores.',
    decisionItSupports: '¿Dónde necesito más supply? ¿Hay conductores subutilizados que puedo redirigir?',
    nextStep: 'Si hay gaps de cobertura, revisa si hay conductores cercanos en Action Queues.',
    dataUnavailableMessage: 'La inteligencia operativa no pudo cargarse. Verifica Data Foundation.',
    audience: 'supervisor, strategy',
  },
  drivers_action_queues: {
    id: 'drivers_action_queues',
    title: 'Action Queues',
    oneLinePurpose: 'Te muestra qué conductores deberían accionarse primero, por qué y con qué prioridad.',
    whatYouCanDo: 'Ver listas priorizadas de conductores por tipo de acción: at risk, churn reciente, declining, no first trip.',
    howToUse: 'Filtra por prioridad y tipo. Los de prioridad CRITICAL y HIGH son los más urgentes. Desde aquí puedes crear campañas.',
    decisionItSupports: '¿A quién contacto primero? ¿Cuál es la acción más urgente hoy?',
    nextStep: 'Selecciona conductores y crea una campaña en Campaign Intelligence.',
    dataUnavailableMessage: 'Las colas accionables no pudieron cargarse. Verifica que los datos de actividad estén actualizados en Data Foundation.',
    audience: 'operator, supervisor',
  },
  drivers_pilot: {
    id: 'drivers_pilot',
    title: 'Operational Pilot',
    oneLinePurpose: 'Te permite crear y gestionar cohorts piloto para probar estrategias antes de escalar.',
    whatYouCanDo: 'Crear cohorts controlados, asignar owners, registrar observaciones y medir resultados.',
    howToUse: 'Crea un piloto con un grupo pequeño. Asigna owners. Ejecuta. Registra aprendizajes antes de escalar.',
    decisionItSupports: '¿Funciona esta estrategia a pequeña escala? ¿Vale la pena escalarla?',
    nextStep: 'Si el piloto fue exitoso, escala a campaña completa en Campaign Intelligence.',
    dataUnavailableMessage: 'El módulo de piloto no pudo cargar datos. Verifica conectividad con la base de datos.',
    audience: 'supervisor',
  },
  drivers_operational_priorities: {
    id: 'drivers_operational_priorities',
    title: 'Operational Priorities',
    oneLinePurpose: 'Te muestra movimientos de conductores priorizados por urgencia operativa.',
    whatYouCanDo: 'Ver qué conductores se movieron entre segmentos y cuáles requieren acción inmediata.',
    howToUse: 'Filtra por prioridad operativa. Los conductores que cayeron de segmento son los más urgentes.',
    decisionItSupports: '¿Quién se deterioró esta semana y necesita intervención inmediata?',
    nextStep: 'Prioriza a los que cayeron y crea campaña si hay suficientes.',
    dataUnavailableMessage: 'Las prioridades operativas no pudieron calcularse. Verifica la fuente de migración de segmentos.',
    audience: 'supervisor',
  },
  drivers_operational_workflows: {
    id: 'drivers_operational_workflows',
    title: 'Operational Workflows',
    oneLinePurpose: 'Te permite gestionar el flujo de trabajo operativo de cada caso asignado.',
    whatYouCanDo: 'Ver estado de workflows, asignaciones pendientes y acciones registradas por caso.',
    howToUse: 'Revisa tus workflows asignados. Actualiza el estado de cada caso después de cada acción.',
    decisionItSupports: '¿Qué casos tengo pendientes? ¿Cuál es el siguiente paso en cada uno?',
    nextStep: 'Actualiza el estado de tus casos y registra el resultado de cada contacto.',
    dataUnavailableMessage: 'Los workflows no pudieron cargarse. Verifica la conectividad.',
    audience: 'operator',
  },
  drivers_campaign_intelligence: {
    id: 'drivers_campaign_intelligence',
    title: 'Campaign Intelligence',
    oneLinePurpose: 'Te permite crear una campaña a partir de conductores priorizados. Aquí defines el universo que consumirá el CRM.',
    whatYouCanDo: 'Crear campañas, previsualizar universos, revisar el estado operativo de cada campaña y exportar al CRM.',
    howToUse: 'Elige queues fuente, filtra por país/ciudad/prioridad, previsualiza, y crea la campaña. Luego exporta al CRM.',
    decisionItSupports: '¿Con quién hago campaña? ¿El universo es viable? ¿Está lista para el CRM?',
    nextStep: 'Después de crear, revisa el Operating Board y exporta la lista al CRM.',
    dataUnavailableMessage: 'Campaign Intelligence no pudo cargar. Verifica que las colas accionables y la fuente de datos estén disponibles.',
    audience: 'supervisor, operator',
  },
  drivers_crm_bridge: {
    id: 'drivers_crm_bridge',
    title: 'CRM Bridge',
    oneLinePurpose: 'Te permite exportar la campaña al CRM y recibir los resultados del contacto.',
    whatYouCanDo: 'Exportar listas, monitorear estado de sincronización, importar resultados del contacto.',
    howToUse: 'Verifica que la campaña esté lista. Exporta al CRM. Cuando el CRM termine, importa los resultados aquí.',
    decisionItSupports: '¿El CRM recibió la lista? ¿Ya devolvió resultados? ¿Hay errores de sync?',
    nextStep: 'Después de importar resultados, revisa Campaign Effectiveness para ver el cambio observado.',
    dataUnavailableMessage: 'El bridge CRM no pudo conectarse. Verifica que el servicio de sincronización esté operativo.',
    audience: 'operator, supervisor',
  },
  drivers_campaign_effectiveness: {
    id: 'drivers_campaign_effectiveness',
    title: 'Resultado Observado',
    oneLinePurpose: 'Te permite revisar si después de la campaña los conductores volvieron a operar.',
    whatYouCanDo: 'Ver cambio observado en viajes, tasa de reactivación y comparación antes/después por conductor.',
    howToUse: 'Selecciona una campaña y una ventana de medición (D+7, D+14). Revisa si hubo cambio en el comportamiento.',
    decisionItSupports: '¿La campaña tuvo efecto observable? ¿Vale la pena repetirla? ¿Debo cambiar el approach?',
    nextStep: 'Si el resultado fue bueno, repite con un universo similar. Si no, ajusta targeting o canal.',
    dataUnavailableMessage: 'Los resultados no pudieron calcularse. Puede que la ventana de medición aún no se haya cumplido.',
    audience: 'supervisor, strategy',
  },
  drivers_data_foundation: {
    id: 'drivers_data_foundation',
    title: 'Data Foundation',
    oneLinePurpose: 'Te dice si la data base de Drivers está fresca, completa y confiable.',
    whatYouCanDo: 'Ver estado de cada fuente operativa: cuándo se actualizó, si hay datos faltantes, si hay bloqueos.',
    howToUse: 'Revisa que todas las fuentes estén en verde. Si alguna está en rojo o amarillo, los datos pueden estar desactualizados.',
    decisionItSupports: '¿Puedo confiar en lo que veo en las otras pestañas? ¿Los datos están frescos?',
    nextStep: 'Si hay fuentes bloqueadas, reporta al equipo técnico antes de tomar decisiones operativas.',
    dataUnavailableMessage: 'No se pudo verificar el estado de las fuentes. Contacta al equipo técnico.',
    audience: 'admin, supervisor',
  },
  drivers_operational_health: {
    id: 'drivers_operational_health',
    title: 'Operational Health',
    oneLinePurpose: 'Te muestra si los servicios y endpoints de Drivers están funcionando correctamente.',
    whatYouCanDo: 'Ver estado de salud de cada servicio: tiempos de respuesta, errores, disponibilidad.',
    howToUse: 'Si una pestaña no carga, revisa aquí si el servicio correspondiente está caído o lento.',
    decisionItSupports: '¿El sistema está operativo? ¿Hay algo caído que explica por qué no puedo ver datos?',
    nextStep: 'Si un servicio está caído, reporta al equipo técnico. Los datos no disponibles no se perdieron.',
    dataUnavailableMessage: 'El health check no pudo ejecutarse. Verifica la conectividad general del sistema.',
    audience: 'admin',
  },
  drivers_capability_governance: {
    id: 'drivers_capability_governance',
    title: 'Capability Governance',
    oneLinePurpose: 'Te muestra qué capacidades de Drivers están maduras, en construcción, futuras o bloqueadas.',
    whatYouCanDo: 'Ver el mapa completo de capacidades con su estado de madurez y dependencias.',
    howToUse: 'Consulta el estado de cada capacidad. Las que están en "Production Ready" son confiables. Las demás están en desarrollo.',
    decisionItSupports: '¿Qué puedo usar con confianza hoy? ¿Qué está en camino?',
    nextStep: 'Usa solo las capacidades marcadas como producción. Las demás son experimentales.',
    dataUnavailableMessage: 'El mapa de capacidades no pudo cargarse. Esto es informativo, no bloquea la operación.',
    audience: 'admin, strategy',
  },
  drivers_operator: {
    id: 'drivers_operator',
    title: 'Vista Operador',
    oneLinePurpose: 'Vista enfocada para el operador de campo: qué hacer hoy.',
    whatYouCanDo: 'Ver tus casos asignados, contactar conductores en orden de prioridad, registrar resultados.',
    howToUse: 'Revisa "My Work Today" y contacta en orden. Registra cada resultado inmediatamente.',
    decisionItSupports: '¿Qué hago ahora? ¿A quién contacto primero?',
    nextStep: 'Después de contactar, registra el resultado y pasa al siguiente caso.',
    dataUnavailableMessage: 'Tu vista de trabajo no pudo cargar. Verifica la conexión o contacta al supervisor.',
    audience: 'operator',
  },
  drivers_supervisor: {
    id: 'drivers_supervisor',
    title: 'Vista Supervisor',
    oneLinePurpose: 'Vista de supervisión: cómo va el equipo y qué está trabado.',
    whatYouCanDo: 'Ver avance de cada operador, campañas activas, casos bloqueados, sync CRM.',
    howToUse: 'Revisa el dashboard de ejecución. Identifica operadores con atraso y campañas sin movimiento.',
    decisionItSupports: '¿Mi equipo está avanzando? ¿Hay algo trabado que necesito desbloquear?',
    nextStep: 'Desbloquea los casos trabados y redistribuye si hay desbalance.',
    dataUnavailableMessage: 'La vista de supervisión no pudo cargar. Verifica conectividad.',
    audience: 'supervisor',
  },
  drivers_strategy: {
    id: 'drivers_strategy',
    title: 'Vista Estrategia',
    oneLinePurpose: 'Vista analítica para decisiones de crecimiento y efectividad.',
    whatYouCanDo: 'Analizar tendencias de supply, efectividad de campañas, y patrones de comportamiento.',
    howToUse: 'Revisa métricas de largo plazo. Identifica qué tipo de campañas y segmentos dan mejor resultado.',
    decisionItSupports: '¿Qué estrategias funcionan? ¿Dónde invertir más esfuerzo?',
    nextStep: 'Ajusta la estrategia de campañas basándote en los resultados observados.',
    dataUnavailableMessage: 'La vista analítica no pudo cargar. Verifica conectividad.',
    audience: 'strategy',
  },
  drivers_admin: {
    id: 'drivers_admin',
    title: 'Vista Admin / Data',
    oneLinePurpose: 'Vista de gobernanza: verificar que el sistema y los datos son confiables.',
    whatYouCanDo: 'Revisar salud del sistema, frescura de datos, estado de capacidades.',
    howToUse: 'Verifica que todo esté en verde antes de que el equipo operativo trabaje.',
    decisionItSupports: '¿Puedo confiar en el sistema hoy? ¿Hay algo roto?',
    nextStep: 'Si hay problemas, notifica al equipo antes de que afecte la operación.',
    dataUnavailableMessage: 'La vista admin no pudo cargar. Verifica la conectividad general.',
    audience: 'admin',
  },
}

export function getTabGuide (tabKey) {
  return DRIVER_TAB_GUIDE_REGISTRY[tabKey] || null
}

export default DRIVER_TAB_GUIDE_REGISTRY
